ALTER TABLE RESTAURANT
	ADD CONSTRAINT CapacityIsPositive CHECK(CAPACITY > 0),
	ADD CONSTRAINT ClosingAfterOpen CHECK(CLOSE_TIME > OPEN_TIME)

ALTER TABLE RESTAURANT
	ADD CONSTRAINT CITY_EXISTS CHECK(CITYID IS NOT NULL)


ALTER TABLE FOOD
	ADD CONSTRAINT NAME_IS_UNIQUE UNIQUE(NAME),
	ADD CONSTRAINT CATEGORY_EXISTS CHECK(FoodCategoryId IS NOT NULL),
	ADD CONSTRAINT PriceNotNegative CHECK(PRICE > 0)

ALTER TABLE Restaurant_Food
	ADD CONSTRAINT NOT_NULL CHECK(RestaurantId IS NOT NULL AND FoodId IS NOT NULL AND Is_Available IS NOT NULL)

ALTER TABLE Order_Items
	ADD CONSTRAINT AMOUNTNOTNEGATIVE CHECK(Amount>0),
	ADD CONSTRAINT NOT_NULL CHECK(ORDERID IS NOT NULL AND FOODID IS NOT NULL)
	
ALTER TABLE EMPLOYEE
	ADD CONSTRAINT approve_worker_position CHECK (
		(jobId != 1 OR FLOOR((CURRENT_DATE - DateOfBirth) / 365.25) > 18) AND
		(jobId != 3 OR Has_DriversLiscence = TRUE)
	)
ALTER TABLE DELIVERIES
	ADD CONSTRAINT address_not_null CHECK(Adress IS NOT NULL)

ALTER TABLE Delivery_Review
	ADD CONSTRAINT RATING_WITHIN_BOUNDS CHECK(Review >= 1 AND Review <= 5)

ALTER TABLE Food_Review
	ADD CONSTRAINT RATING_WITHIN_BOUNDS CHECK(Rating >= 1 AND Rating<= 5)
	