ALTER TABLE RESTAURANT
	ADD CONSTRAINT CapacityIsPositive CHECK(CAPACITY > 0),
	ADD CONSTRAINT ClosingAfterOpen CHECK(CLOSE_TIME > OPEN_TIME)

ALTER TABLE RESTAURANT
	ADD CONSTRAINT CITY_EXISTS CHECK(CITYID IS NOT NULL)


ALTER TABLE FOOD
	ADD CONSTRAINT NAME_IS_UNIQUE UNIQUE(NAME),
	ADD CONSTRAINT CATEGORY_EXISTS CHECK(FoodCategoryId IS NOT NULL),
	ADD CONSTRAINT PriceNotNegative CHECK(PRICE > 0)

ALTER TABLE Restaurant_Food
	ADD CONSTRAINT NOT_NULL CHECK(RestaurantId IS NOT NULL AND FoodId IS NOT NULL AND Is_Available IS NOT NULL)